# Generated by Django 3.2.5 on 2022-09-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcaciaLen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dat', models.DateField(blank=True, null=True)),
                ('sum_len', models.DecimalField(blank=True, decimal_places=2, max_digits=28, null=True)),
                ('frac_len', models.DecimalField(blank=True, decimal_places=2, max_digits=31, null=True)),
            ],
            options={
                'db_table': 'acacia_len',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AggdryLength',
            fields=[
                ('rm_rounded', models.DecimalField(db_column='rm-rounded', decimal_places=2, max_digits=5, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'aggdry_length',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AllLen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thedate', models.DateField(blank=True, null=True)),
                ('isleta_sum_len', models.DecimalField(blank=True, decimal_places=2, max_digits=28, null=True)),
                ('isleta_frac_len', models.DecimalField(blank=True, decimal_places=2, max_digits=31, null=True)),
                ('acacia_sum_len', models.DecimalField(blank=True, decimal_places=2, max_digits=28, null=True)),
                ('acacia_frac_len', models.DecimalField(blank=True, decimal_places=2, max_digits=31, null=True)),
                ('combined_sum_len', models.DecimalField(blank=True, decimal_places=2, max_digits=29, null=True)),
                ('combined_frac_len', models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True)),
            ],
            options={
                'db_table': 'all_len',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DischargeGsa',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('discharge_cfs', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'discharge_gsa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DryLength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rm_up', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rm_down', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dry_length', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('dat', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dry_length',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dryness',
            fields=[
                ('dryid', models.IntegerField(primary_key=True, serialize=False)),
                ('extent', models.CharField(blank=True, max_length=10, null=True)),
                ('down_dryid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dryness',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('feature', models.TextField(blank=True, null=True)),
                ('featype', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'db_table': 'feature',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FeatureRm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rm_rounded', models.DecimalField(blank=True, db_column='rm-rounded', decimal_places=1, max_digits=22, null=True)),
                ('feature', models.TextField(blank=True, db_collation='utf8mb4_0900_ai_ci', null=True)),
            ],
            options={
                'db_table': 'feature_rm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IsletaLen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dat', models.DateField(blank=True, null=True)),
                ('sum_len', models.DecimalField(blank=True, decimal_places=2, max_digits=28, null=True)),
                ('frac_len', models.DecimalField(blank=True, decimal_places=2, max_digits=31, null=True)),
            ],
            options={
                'db_table': 'isleta_len',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fulcrum_id', models.CharField(blank=True, max_length=38, null=True)),
                ('obstype', models.CharField(blank=True, max_length=38, null=True)),
                ('datet', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'observation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('photos_gen_url', models.CharField(blank=True, max_length=2083, null=True)),
            ],
            options={
                'db_table': 'photos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reach',
            fields=[
                ('reaid', models.AutoField(primary_key=True, serialize=False)),
                ('reach', models.CharField(blank=True, max_length=10, null=True)),
                ('downstream_rm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'reach',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Remnant',
            fields=[
                ('remid', models.AutoField(primary_key=True, serialize=False)),
                ('approximate_area_sq_feet', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'remnant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rivermile',
            fields=[
                ('rm', models.DecimalField(decimal_places=2, max_digits=5, primary_key=True, serialize=False)),
                ('position', models.TextField()),
                ('latlong', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rivermile',
                'managed': False,
            },
        ),
    ]
